eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - AuthFilter
        - id: issue-tracker-service
          uri: lb://issue-tracker-service
          predicates:
            - Path=/api/issue-tracker/**
          filters:
            - AuthFilter
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
server:
  port: 8080
