server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Victin09/vpm
          search-paths:
            - /backend/config-cloud-data
  application:
    name: config-cloud-service
